### ISSUE TITLE
add username to table on /posts page

### ISSUE THREAD

**Issue by einariii** [einariii/beamscene#69]
line 11 on
lib/blog_web/templates/posts/index.html.heex

@lgmfred current implementation not working

**Comment by einariii** [comment]
refer to latest commit on [67-outstanding](https://github.com/einariii/beamscene/tree/67-outstanding)

**Comment by lgmfred** [comment]
That can easily be fixed by adding `posts = Posts.list_posts(title) |> Repo.preload([:user])` and `posts = Posts.list_posts() |> Repo.preload([:user])` in the two clauses of `index/2` inside the `posts_controller.ex`.  I initially focused on adding the username when viewing/reading one particular post that's why the bug sneaked past.

**Comment by einariii** [comment]
merci bien
